version: '3.8'

services:
  # Web Application
  webapp:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: socialdiet_webapp
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SocialDietDB;User Id=sa;Password=YourStrongPassword123;TrustServerCertificate=True
      - Redis__ConnectionString=redis:6379
      - Elasticsearch__Url=http://elasticsearch:9200
    depends_on:
      - sqlserver
      - redis
      - elasticsearch
    networks:
      - socialdiet_network

  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: socialdiet_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - socialdiet_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: socialdiet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - socialdiet_network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: socialdiet_elasticsearch
    environment:
      - node.name=es01
      - cluster.name=social-diet-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - socialdiet_network

volumes:
  sqlserver_data:
  redis_data:
  elasticsearch_data:

networks:
  socialdiet_network:
    driver: bridge 